# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest
    steps:
    - name: Test
      run: |
        ls "C:\Program Files\Git\mingw64\bin"
        ls "C:\Strawberry\c\bin"
        ls "C:\Strawberry\perl\bin"
        ls "C:\ProgramData\Chocolatey\lib\mingw\tools\install\mingw64\bin"
        where libstdc++-6.dll
        
        
