# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest
    steps:
    - name: Test
      run: |
        ls C:\Program Files (x86)
        ls C:\Program Files
        
