name: qt

on:
  push:
    branches:
      - master

jobs:
  qt:
    runs-on: ubuntu-18.04

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.13.0
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.13.1"
      - uses: actions/checkout@v2
      - name: Test
        env:
          QT_DIR: ${{ github.workspace }}${{ '/Qt' }}
        run: |
          echo '11111'
          echo $Qt5_DIR
          echo $QT_DIR
          echo $RUNNER_WORKSPACE
          echo '22222'
          cd $RUNNER_WORKSPACE
          pwd
          ls -al
          ls -al Qt
          ls -al github-actions-demo
