name: qt

on:
  push:
    branches:
      - master

jobs:
  qt:
    runs-on: ubuntu-18.04

    steps:
      - name: Cache QT Docker
        id: cache-qt-docker
        uses: actions/cache@v2
        with:
          path: /var/lib/docker
          key: ${{ runner.os }}-docker-qt

      - name: Pull QT Docker
        if: steps.cache-qt-docker.outputs.cache-hit != 'true'
        run: |
          docker pull therecipe/qt:windows_64_static
          docker pull therecipe/qt:linux_static

      # - name: Install Qt
      #   uses: jurplel/install-qt-action@v2
      #   with:
      #     version: 5.13.0

      - uses: actions/setup-go@v2
        with:
          go-version: "^1.13.1"

      - uses: actions/checkout@v2

      - name: Build
        run: |
          go get -v github.com/therecipe/qt/cmd/...
          $(go env GOPATH)/bin/qtdeploy -docker build linux_static ./cmd/qt
          $(go env GOPATH)/bin/qtdeploy -docker build windows_64_static ./cmd/qt
          ls -al ./cmd/qt/deploy/linux
          ls -al ./cmd/qt/deploy/windows
